name: Schedule team meetings
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: wesleytodd/meeting-maker@v0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        schedules: '2020-04-02T17:00:00.0Z/P7D'
        issueTitle: 'Node.js Foundation Web Server Team Meeting <%= date.toFormat("yyyy-MM-dd") %>'
        agendaLabel: 'web-server-frameworks-agenda'
